### ISSUE TITLE
Probleme authentification

### ISSUE THREAD

**Issue by lepekinoi** [geogeocutcut/jeedom-cozytouch-plugin#15]
Bonjour,

Souci d'authentification suivant:
-> Jeedom a jour (4.3.12)
-> plugin a jour 12/12/2022

<img width="1088" alt="Capture d’écran 2022-12-15 221237" src="https://user-images.githubusercontent.com/59528735/207968306-72521c4b-0692-4981-9b94-d385d3f406b9.png">

Suis je seul  dans ce cas ?

**Comment by MADomotique** [comment]
You're not alone

**Comment by lepekinoi** [comment]
Tout semble ok, les commandes ne sont plus en erreur 1 a 2 journée + tard.
Je trouve que les serveurs Cozytouch ne sont pas très stable et donc les services pas réactifs, pour une plateforme en production, le dev devrait être testé plus avant de pousser des MAJ surtout sur des prédiodes hivernales.
--> pas de correctif nécéssaire. Merci
