### ISSUE TITLE
Class 'object' not found

### ISSUE THREAD

**Issue by ckd77** [geogeocutcut/jeedom-cozytouch-plugin#3]
Bonjour

Pour info, je suis sousDebian duster, php 7.3, jeedom 4 pour test.

Le plugin a le problème de Class 'object' not found ;) 
Ce qui est gênant, car le plugin ne fonctionne pas pour le coup, mais je sais très bien que que jeedom 4 est pas en stable non plus ;) Ce message est a titre d'information, en espérant qu'une correction soit faite :)

**Comment by pnizet** [comment]
meme probleme ici.
Est ce que vous prévoyez de rendre compatible votre plug in avec la nouvelle version de jeedom ?
Je viens tout juste de me lancer dans la mise en place d'une box jeedom avec cozytouch pour gerer mes radiateurs et au premier plugin installé, patatra ! ca ne fonctionne pas :'(
Merci.

**Comment by pnizet** [comment]
une combine qui consiste à modifier le code du plugin en local vient d'etre partagée sur le forum : https://community.jeedom.com/t/plug-in-cozy-touch/4466/22
Ca m'a l'air d'être un peu une bidouille, mais si ne l'ai pas, il faudrait peut etre mettre à jour le plugin avec ce qui vient d'étre partagé, non ?

**Comment by guikcd** [comment]
Jeedom 4 est maintentant stable et il est difficile d'installer autre chose que php 7.x.
J'ai proposé le changement via https://github.com/geogeocutcut/jeedom-cozytouch-plugin/pull/4.

Pour ceux qui veulent l'inclure facilement :

* aller dans le dossier des plugins et plus précisément dans celui de cozytouch (ex.: `/usr/share/nextdom/plugins/cozytouch/desktop/php/`)
* récupérer la modification
```
wget https://patch-diff.githubusercontent.com/raw/geogeocutcut/jeedom-cozytouch-plugin/pull/4.diff
```
* appliquer la modification
```
patch < 4.diff # installer patch s'il n'est pas présent sur votre système
```

**Comment by guikcd** [comment]
Le soucis a en fait été corrigé : 8434892b43291d68c5be0ab4256962c8be1cf3e8
